FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
COPY packages/ ./packages/
COPY apps/api/ ./apps/api/

RUN npm install
RUN npx tsc -p packages/shared-types
RUN npx tsc -p packages/language
RUN npx tsc -p packages/risk-engine
RUN npx tsc -p packages/voice
RUN npx tsc -p packages/ai-agent
RUN npx tsc -p apps/api

FROM node:20-alpine AS runner
WORKDIR /app
COPY --from=builder /app ./
EXPOSE 3000
CMD ["node", "apps/api/dist/main.js"]
